include: package:pedantic/analysis_options.yaml

analyzer:
  exclude:
    [
      example/**,
      dibbs_cli_example/**,
    ]

linter:
  rules:
    prefer_single_quotes: false
    public_member_api_docs: false
    prefer_relative_imports: false
    avoid_classes_with_only_static_members: false
    lines_longer_than_80_chars: false
    avoid_relative_lib_imports: false
    type_annotate_public_apis: false
    avoid_positional_boolean_parameters: false
    prefer_interpolation_to_compose_strings: false
    omit_local_variable_types: false
    avoid_catches_without_on_clauses: false

