name: dibbs_flutter_cli
description: "Dibbs CLI tool"
version: 1.0.7
repository: https://github.com/denisviana/dibbs_flutter_cli

environment:
  sdk: '>=2.16.2 <3.0.0'

executables:
  dibbs: main

dependencies:
  equatable: ^2.0.3
  recase: ^4.0.0
  ansicolor: ^2.0.1
  http: ^0.13.4
  path: ^1.8.1
  yaml: ^3.1.0
  args: ^2.3.0
  dart_console: ^1.0.0
  tuple: ^2.0.0
  pubspec_yaml: ^3.1.0
  fhir_yaml: ^0.7.0
  rxdart: ^0.27.3
  gql: ^0.13.1
  glob: ^2.0.2
  build: ^2.3.0
  deep_collection: ^1.0.2
  ms_map_utils: ^1.1.0
  flinq: ^2.0.2
  decimal: ^2.1.0

dev_dependencies:
  test: ^1.20.1
  pedantic: ^1.11.1

vars:
  format_files: flutter format --line-length 100 ./lib/app/ ./lib/core/ ./lib/main.dart ./lib/main_dev.dart ./lib/init_core_modules.dart ./test
  analyze: flutter analyze .
  run_tests: flutter tests
  push: git push

scripts:
  format: $format_files
  build_runner: flutter pub run build_runner build --delete-conflicting-outputs
  git_push: $format_files & $analyze & $run_tests & $push